---
- name: add win user
  hosts: windows_desktops
  tasks: 
    - name: create windows account
      ansible.windows.win_user: 
        name: DesktopUser1
        password: WGU123
        state: present
        groups:
          - Administrators
      when: ansible_host=="10.10.1.35"
    - name: create windows account
      ansible.windows.win_user: 
        name: DesktopUser2
        password: WGU123
        state: present
        groups:
          - Administrators
      when: ansible_host=="10.10.1.36"
    - name: create windows account
      ansible.windows.win_user: 
        name: DesktopUser3
        password: WGU123
        state: present
        groups:
          - Administrators
      when: ansible_host=="10.10.1.43"
    - name: create windows account
      ansible.windows.win_user: 
        name: DesktopUser4
        password: WGU123
        state: present
        groups:
          - Administrators
      when: ansible_host=="10.10.1.29"
